# SENTINEL — Zero Harm
# System Configuration
# All thresholds and constants live here
# Change values here to adjust system behaviour globally

import os
from dotenv import load_dotenv

# Resolve and load .env from the project root
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

# RISK THRESHOLDS
CAUTION_THRESHOLD = 41
WARNING_THRESHOLD = 61
HIGH_RISK_THRESHOLD = 76
CRITICAL_THRESHOLD = 86
EMERGENCY_THRESHOLD = 95

# GAS PPM THRESHOLDS
GAS_LOW = 50
GAS_MEDIUM = 200
GAS_HIGH = 500
GAS_CRITICAL_LEL_PERCENT = 10

# TEMPERATURE THRESHOLDS
TEMP_LOW = 40
TEMP_HIGH = 60

# WORKER THRESHOLDS
WORKER_SCORE_CAP = 10
WORKER_MULTIPLIER = 2
WORKER_HIGH_COUNT = 3

# COMPOUND BONUS VALUES
BONUS_HOT_WORK_GAS = 15
BONUS_CONFINED_GAS = 15
BONUS_WORKERS_HEAT = 10
BONUS_TRIPLE_THREAT = 20
BONUS_ELECTRICAL_GAS = 10
BONUS_NIGHT_SHIFT = 5

# TREND PREDICTOR
TREND_WINDOW_SIZE = 5
TREND_PROJECTION_MINUTES = 15
TREND_CRITICAL_GAS = 500
TREND_INTERVAL_SECONDS = 30

# RAG SETTINGS
RAG_TRIGGER_SCORE = 75
RAG_TOP_K = 3
FAISS_INDEX_PATH = "models/faiss_index/"
EMBEDDINGS_CACHE_PATH = "models/embeddings_cache/"
CORPUS_PATH = "data/corpus/"

# SIMILARITY ENGINE
SIMILARITY_TRIGGER_SCORE = 40
SIMILARITY_HIGH_THRESHOLD = 70

# WORKER SAFETY
WORKER_EXPOSURE_TRIGGER = 60
EXPOSURE_CRITICAL_MINUTES = 10

# ORCHESTRATOR
ORCHESTRATOR_TRIGGER = 85
PERMIT_LOCK_TIMEOUT = 3600

# DATABASE
DATABASE_PATH = "data/database/sentinel.db"
REPLAY_INTERVAL_SECONDS = 30

# GEMINI
GEMINI_MODEL = "gemini-2.0-flash"
GEMINI_MAX_TOKENS = 1000
